spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        default_batch_size: 2
        format_sql: true
jwt:
  secret: abcdegfhikmlmlmlmllmlmlmllmlmlllllllllllllllllll
  expiration: 1000000000000
